main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import TopPageView, TopGraphDataView, TaskAddView, TaskDetailView, TaskLabelAddView
from .views import ActualDataAddView, ActualDataEditView

app_name = "main"

urlpatterns = [
    path('', TopPageView.as_view(), name="top_page"),
    path('task/add/', TaskAddView.as_view(), name="task_add"),
    path(r'task/detail/<int:pk>/',
         TaskDetailView.as_view(), name="task_detail"),
    path(r'actualdata/add/<int:parent_task_pk>/',
         ActualDataAddView.as_view(), name="actual_data_add"),
    path(r'actualdata/edit/<int:pk>/',
         ActualDataEditView.as_view(), name="actual_data_edit"),
    path('label/add/', TaskLabelAddView.as_view(), name="label_add"),
    path('api/topgraphdata/', TopGraphDataView.as_view(), name="top_graph_data"),
]

todomanager/urls.py
from django.contrib import admin
from django.urls import path, include
from todomanager import settings

urlpatterns = [
    path(settings.BASE_URL_PATH, include('main.urls', namespace='main')),
    path(settings.BASE_URL_PATH + 'admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django import forms
from datetime import date, timedelta
import bootstrap_datepicker_plus as datetimepicker
import markdown
import jpholiday


def is_business_day(value: date):
    if value.weekday() >= 5:  # 土日
        return False
    if jpholiday.is_holiday(value):
        return False
    return True


def get_business_days(start: date, end: date):
    if end < start:
        raise ValueError("get_business_days: end < start")
    else:
        result = []
        for i in range((end - start).days + 1):
            value = start + timedelta(days=i)
            if (is_business_day(value)):
                result.append(start + timedelta(days=i))
        return result


# start_dateからend_dateまでの営業日数を返す
def get_business_days_count(day1: date, day2: date):
    if day1 <= day2:
        return len(get_business_days(day1, day2)) - 1
    else:
        return -len(get_business_days(day2, day1)) + 1


class TaskLabel(models.Model):
    name = models.CharField(max_length=128, verbose_name="ラベル名")
    color = models.CharField(max_length=32, verbose_name="色")

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=128, verbose_name="タイトル")
    start_date = models.DateField(verbose_name="開始日", default=date.today)
    target_date = models.DateField(verbose_name="期日", default=date.today)
    assumed_workload = models.FloatField(verbose_name="予定工数（時間）")
    note = models.TextField(verbose_name="ノート", blank=True)
    labels = models.ManyToManyField(TaskLabel, verbose_name="ラベル",
                                    related_name="tasks", blank=True)
    color = models.CharField(
        max_length=32, verbose_name="色", default="#ffffff")

    def __str__(self):
        return self.title

    def get_note_html(self):
        md = markdown.Markdown()
        return md.convert(self.note)

    # 残日数。
    def remaining_days(self, end_date=None, allow_zero=True):
        if end_date is None:
            value = get_business_days_count(date.today(), self.target_date)
        else:
            value = get_business_days_count(end_date, self.target_date)
        return value if value < 0 or allow_zero else value + 1

    # end_date時点までの総進捗。
    def total_actual_progress(self, end_date=None):
        use_date = end_date if end_date is not None else date.today()
        ret = self.actual_data.filter(input_date__lte=use_date).aggregate(
            models.Sum("progress"))
        value = ret["progress__sum"]
        if value is None:
            return 0
        elif value > 100:
            return 100
        elif value < 0:
            return 0
        else:
            return round(value, 0)

    # end_date時点までの総実績工数。
    def total_actual_workload(self, end_date=None):
        use_date = end_date if end_date is not None else date.today()
        total_actual_progress = self.total_actual_progress(use_date)
        ret = self.actual_data.filter(input_date__lte=use_date).aggregate(
            models.Sum("actual_workload"))
        value = ret["actual_workload__sum"]
        if value is None:
            return 0
        elif total_actual_progress < 0.001:
            # 合計進捗が0%以下のとき、例外的に実績工数は0とする。
            return 0
        else:
            return value

    # end_date時点での予測総工数。
    def predicted_total_workload(self, end_date=None):
        use_date = end_date if end_date is not None else date.today()
        total_actual_workload = self.total_actual_workload(use_date)
        total_actual_progress = self.total_actual_progress(use_date)
        if end_date is not None and end_date < self.start_date:
            return 0
        elif total_actual_progress < 0.001:
            # 合計進捗が0%以下のとき、例外的に予測残工数は予定工数とする。
            return self.assumed_workload
        else:
            return round(total_actual_workload * 100 / total_actual_progress, 1)

    # end_date時点での予測残工数。
    def predicted_remaining_workload(self, end_date=None):
        use_date = end_date if end_date is not None else date.today()

        if use_date <= date.today():
            predicted_total_workload = self.predicted_total_workload(use_date)
            total_actual_workload = self.total_actual_workload(use_date)
            return round(predicted_total_workload - total_actual_workload, 1)
        else:
            predicted_total_workload = self.predicted_total_workload(
                date.today())
            total_actual_workload = self.total_actual_workload(date.today())
            last_remaining_workload = predicted_total_workload - total_actual_workload
            remain_total_days = self.remaining_days(date.today()) + 1
            remain_current_days = self.remaining_days(use_date) + 1
            if remain_total_days > 0:
                value = round(last_remaining_workload *
                              remain_current_days / remain_total_days, 1)
                return value if value > 0 else 0
            else:
                return 0

    # end_date時点での残一日あたりの工数。
    def predicted_workload_per_day(self, end_date=None):
        use_date = end_date if end_date is not None else date.today()
        remain_current_days = self.remaining_days(use_date) + 1
        if remain_current_days > 0:
            value = self.predicted_remaining_workload(
                use_date) / remain_current_days
            return round(value, 1)
        else:
            return 0

    # end_dateの実績工数（未来日時の場合は予測１日あたり工数。）
    def actual_workload(self, end_date=None):
        use_date = end_date if end_date is not None else date.today()
        if use_date <= date.today():
            ret = self.actual_data.filter(input_date=use_date).aggregate(
                models.Sum("actual_workload"))
            value = ret["actual_workload__sum"]
            if value is None or value < 0:
                return 0
            else:
                return round(value, 1)
        else:
            return self.predicted_workload_per_day(end_date)

    # end_dateの進捗
    def actual_progress(self, end_date=None):
        use_date = end_date if end_date is not None else date.today()
        if use_date <= date.today():
            ret = self.actual_data.filter(input_date=use_date).aggregate(
                models.Sum("progress"))
            value = ret["progress__sum"]
            if value is None or value < 0:
                return 0
            else:
                return round(value, 0)
        else:
            return self.predicted_workload_per_day(end_date)


class ActualData(models.Model):
    input_date = models.DateField(verbose_name="投入日", default=date.today)
    actual_workload = models.FloatField(verbose_name="実績工数")
    progress = models.FloatField(verbose_name="進捗増分")
    note = models.TextField(verbose_name="ノート", blank=True)

    parent_task = models.ForeignKey(Task, verbose_name="親タスク",
                                    related_name="actual_data",
                                    on_delete=models.CASCADE)

    class Meta:
        ordering = ['-input_date', '-pk']

    def __str__(self):
        return "{} ({}h {}%)".format(self.input_date,
                                     self.actual_workload,
                                     self.progress)

    def get_note_html(self):
        md = markdown.Markdown()
        return md.convert(self.note)


class TaskAddForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'start_date', 'target_date',
                  'assumed_workload', 'note', 'labels', 'color')
        widgets = {
            'title': forms.TextInput(attrs={'size': 128}),
            'color': forms.TextInput(attrs={'type': 'color'}),
            'start_date': datetimepicker.DatePickerInput(
                format='%Y-%m-%d',
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                }),
            'target_date': datetimepicker.DatePickerInput(
                format='%Y-%m-%d',
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                }),
            'assumed_workload': forms.NumberInput(attrs={'step': '0.5'}),
            'note': forms.Textarea(attrs={'cols': 80, 'rows': 6}),
            'labels': forms.CheckboxSelectMultiple
        }


class TaskLabelAddForm(forms.ModelForm):
    class Meta:
        model = TaskLabel
        fields = ('name', 'color')
        widgets = {
            'name': forms.TextInput(attrs={'size': 128}),
            'color': forms.TextInput(attrs={'type': 'color'})
        }


class ActualDataAddForm(forms.ModelForm):
    class Meta:
        model = ActualData
        fields = ('input_date', 'actual_workload', 'progress', 'note')
        widgets = {
            'input_date': datetimepicker.DatePickerInput(
                format='%Y-%m-%d',
                options={
                    'locale': 'ja',
                    'dayViewHeaderFormat': 'YYYY年 MMMM',
                }),
            'actual_workload': forms.NumberInput(attrs={'step': "0.1"}),
            'progress': forms.NumberInput(attrs={'step': "1"}),
            'note': forms.Textarea(attrs={'cols': 80, 'rows': 6}),
        }

main/views.py
from django.views.generic import TemplateView, CreateView, UpdateView
from django.views import View
from .models import Task, TaskLabel, ActualData
from .models import TaskAddForm, TaskLabelAddForm, ActualDataAddForm
from django.urls import reverse
from datetime import date, timedelta
from django.http import JsonResponse
import jpholiday
import parse
# Create your views here.


class TopPageView(TemplateView):
    template_name = "top_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['remain_task_list'] = []
        context['completed_task_list'] = []
        for task in Task.objects.order_by("target_date", "pk"):
            if task.total_actual_progress() < 100:
                context['remain_task_list'].append(task)
            else:
                context['completed_task_list'].append(task)
        context['all_task_list'] = context['remain_task_list'] + context['completed_task_list']
        return context


class TopGraphDataView(View):
    def color_convert(self, code, alpha):
        base_format = "rgba({} , {} , {} , {})"
        cleansed_code = code.strip()
        if len(cleansed_code) != 7:
            return ""
        else:
            try:
                val_r = parse.parse("{:x}", cleansed_code[1:3]).fixed[0]
                val_g = parse.parse("{:x}", cleansed_code[3:5]).fixed[0]
                val_b = parse.parse("{:x}", cleansed_code[5:7]).fixed[0]
            except Exception:
                return ""
        return base_format.format(val_r, val_g, val_b, alpha)

    def get(self, request, *args, **kwargs):
        param = request.GET.get(key="param", default="total")
        if param == "total":
            title = "予測工数"
        elif param == "perday":
            title = "予測工数/日"
        else:
            title = "実績工数/日"

        end_date = date.today()

        agg_day_list = [end_date]
        counter = 0
        for i in range(1, 100):
            tmp = end_date + timedelta(days=i)
            if tmp.weekday() < 5 and not jpholiday.is_holiday(tmp):
                agg_day_list.append(tmp)
                counter += 1
            if counter >= 30:
                break
        counter = 0
        for i in range(1, 100):
            tmp = end_date - timedelta(days=i)
            if tmp.weekday() < 5 and not jpholiday.is_holiday(tmp):
                agg_day_list.insert(0, tmp)
                counter += 1
            if counter >= 30:
                break

        # 初期化
        result_date = {
            "type": "line",
            "data": {
                "labels": [x.__str__() for x in agg_day_list],
                "datasets": [],
            },
            "options": {
                "title": {
                    "display": True,
                    "text": title
                },
                "tooltips": {
                    "callbacks": {}
                },
                "scales": {
                    "yAxes": [
                        {
                            "ticks": {
                                "beginAtZero": True
                            },
                            "stacked": True
                        }
                    ]
                },
                "plugins": {
                    "filler": {
                        "propagate": True
                    }
                }
            },
            "lineAtIndex": [30]
        }

        for task in Task.objects.order_by('target_date'):
            if task.start_date >= agg_day_list[0] or task.predicted_remaining_workload(agg_day_list[0]) > 0:
                if param == "total":
                    graph_data = [task.predicted_remaining_workload(x) for x in agg_day_list]
                elif param == "perday":
                    graph_data = [task.predicted_workload_per_day(x) for x in agg_day_list]
                else:
                    graph_data = [task.actual_workload(x) for x in agg_day_list]

                result_date["data"]["datasets"].append({
                    "label": task.title,
                    "data": graph_data,
                    "backgroundColor": self.color_convert(task.color, 0.2),
                    "pointBackgroundColor": [
                        (self.color_convert(
                            task.color, 1 if x <= end_date else 0.0)
                         )for x in agg_day_list
                    ],
                    "pointBorderColor": [
                        (self.color_convert(
                            task.color, 1 if x <= end_date else 0.0)
                         )for x in agg_day_list
                    ],
                    "borderColor": self.color_convert(task.color, 1),
                    "borderWidth": 1,
                    "lineTension": 0,
                    "stack": 1,
                    "fill": "origin" if len(result_date["data"]["datasets"]) == 0 else "-1"
                })
        return JsonResponse(result_date)


class TaskAddView(CreateView):
    model = Task
    template_name = "task_add.html"
    form_class = TaskAddForm
    success_url = "/"

class ActualDataAddView(CreateView):
    model = ActualData
    template_name = "actual_data_add.html"
    form_class = ActualDataAddForm
    success_url = "/"

    def form_valid(self, form):
        form.instance.parent_task = Task.objects.get(
            pk=self.kwargs["parent_task_pk"])
        form.save()
        self.success_url = reverse("main:task_detail",
                                   kwargs={'pk': self.kwargs["parent_task_pk"]}
                                   )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = Task.objects.get(
            pk=self.kwargs["parent_task_pk"])
        return context


class ActualDataEditView(UpdateView):
    model = ActualData
    template_name = "actual_data_edit.html"
    form_class = ActualDataAddForm
    success_url = "/"

    def form_valid(self, form):
        self.success_url = reverse("main:task_detail",
                                   kwargs={'pk': form.instance.parent_task.pk}
                                   )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = context['object'].parent_task
        return context

class TaskDetailView(UpdateView):
    model = Task
    template_name = "task_detail.html"
    form_class = TaskAddForm
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sorted_actual_data"] = self.object.actual_data.order_by(
            "-input_date", "-pk")
        self.success_url = reverse("main:task_detail",
                                   kwargs={'pk': self.object.pk}
                                   )
        return context


class TaskLabelAddView(CreateView):
    model = TaskLabel
    template_name = "task_label_add.html"
    form_class = TaskLabelAddForm
    success_url = "/"

main/templates/actual_data_add.html
{% extends 'base_task_ro.html' %}
{% load bootstrap4 %}
{% block actualediter %}
<h4 class="mb-2">実績追加</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="float-right">
        <button class="btn btn-primary" type="submit">登録</button>
    </div>
</form>
{% endblock %}
{% block scripts %}
{{ form.media }}
{% endblock %}

main/templates/actual_data_edit.html
{% extends 'base_task_ro.html' %}
{% load bootstrap4 %}
{% block actualediter %}
<h4 class="mb-2">実績編集</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="float-right">
        <button class="btn btn-primary" type="submit">更新</button>
    </div>
</form>
{% endblock %}
{% block scripts %}
{{ form.media }}
{% endblock %}

main/templates/base.html
{% load static %}
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/font-awesome-animation.min.css' %}">
    <title>タスク管理</title>
    {% block head %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'main:top_page' %}">タスク管理</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false" aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        タスク
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'main:top_page' %}">タスク一覧</a>
                        <a class="dropdown-item" href="{% url 'main:task_add' %}">タスク登録</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        ラベル
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'main:top_page' %}">ラベル一覧</a>
                        <a class="dropdown-item" href="{% url 'main:label_add' %}">ラベル作成</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input type="search" class="form-control mr-sm-2" placeholder="検索..." aria-label="検索...">
                <button type="submit" class="btn btn-outline-success my-2 my-sm-0">検索</button>
            </form>
        </div><!-- /.navbar-collapse -->
    </nav>
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                {% block main %}
                {% endblock %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>

</html>

main/templates/task_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block main %}
<h4>タスク登録</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="float-right">
        <button class="btn btn-primary" type="submit">登録</button>
    </div>
</form>
{% endblock %}
{% block scripts %}
{{ form.media }}
{% endblock %}

main/templates/task_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block main %}
<div class="row">
    <div class="col-md-6">
        <h4 class="mb-2">タスク詳細</h4>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
            <p class="text-right">
                <button class="btn btn-primary" type="submit">更新</button>
            </p>
        </form>
    </div>
    <hr>
    <div class="col-md-6 border-left">
        <h4 class="mb-2">サマリー</h4>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="{{ object.total_actual_progress }}"
                aria-valuemin="0" aria-valuemax="100" style="width:{{ object.total_actual_progress }}%;">
            </div>
        </div>
        実績総工数：{{ object.total_actual_workload }}<br>
        予測総工数：{{ object.predicted_total_workload }}<br>
        予測残工数：{{ object.predicted_remaining_workload }}<br>
        <hr>
        <h4 class="mb-2">実績</h4>
        <p class="text-right">
            <a href="{% url 'main:actual_data_add' object.pk %}"><button class="btn btn-primary">追加</button></a>
        </p>
        {% for item in sorted_actual_data %}
        <div class="card mb-3">
            <div class="card-header">
                <div class="row">
                    <div class="col-lg-6">
                        {{ item.input_date }}
                    </div>
                    <div class="col-lg-6 text-right">
                        <span class="badge badge-secondary">{{ item.actual_workload }}h</span>
                        <span class="badge badge-secondary">{{ item.progress }}%</span>
                        <a href="{% url 'main:actual_data_edit' item.pk %}">
                            <i class="fas fa-lg fa-edit text-primary faa-shake animated-hover"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p class="card-text">
                    {{ item.get_note_html|safe }}
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block scripts %}
{{ form.media }}
{% endblock %}

main/templates/task_label_add.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block main %}
<h4>ラベル作成</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <div class="float-right">
        <button class="btn btn-primary" type="submit">作成</button>
    </div>
</form>
{% endblock %}
{% block scripts %}
{{ form.media }}
{% endblock %}

main/templates/top_page.html
{% extends 'base.html' %}
{% load static %}

{% block main %}


<div class="row">
    <div class="col-md-6">
        <h4 class="mb-2">予測工数</h4>
        <p class="text-right">
            <button class="btn btn-primary" id="button_graph_total">予測工数</button>
            <button class="btn btn-primary" id="button_graph_perday">予測工数/日</button>
            <button class="btn btn-primary" id="button_graph_actual">実績工数/日</button>
        </p>
        <div class="d-flex justify-content-center">
            <div class="spinner-border text-primary mt-4" role="status" id="graph_loading">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <canvas id="myChart" height="250"></canvas>
    </div>
    <hr>
    <div class="col-md-6 border-left">
        <h4 class="mb-2">一覧</h4>
        <p class="text-right">
            <a href="{% url 'main:task_add' %}"><button class="btn btn-primary">登録</button></a>
        </p>

        {% for task in all_task_list %}
        <div class="card mb-3">
            <div class="card-header">
                <div class="row">
                    <div class="col-8">
                        <i class="fas fa-lg fa-thumbtack mx-1" style="color: {{ task.color }};"></i>
                        <a href="{% url 'main:task_detail' task.pk %}">
                            {{ task.title }}
                        </a>
                        {% if task.total_actual_progress == 100 %}
                            <i class="fas fa-check-circle mx-1 text-success"></i>
                        {% else %}
                            <span class="mx-1 badge {% if task.remaining_days >= 3 %} badge-info {% elif task.remaining_days >= 0 %} badge-warning {% else %} badge-danger {% endif %} my-1">{{ task.remaining_days }} 日</span>
                        {% endif %}
                    </div>
                    <div class="col-4 text-right">
                        <a href="{% url 'main:actual_data_add' task.pk %}"><i
                                class="fas fa-lg fa-plus mx-1 text-primary faa-flash animated-hover"></i></a>
                        <a href="{% url 'main:task_detail' task.pk %}"><i
                                class="fas fa-lg fa-edit mx-1 text-primary faa-wrench animated-hover"></i></a>
                        <a href="#"><i class="fas fa-lg fa-trash-alt mx-1 text-danger faa-wrench animated-hover"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-xl-8">
                        <small>{{ task.get_note_html|safe }}</small>
                    </div>
                    <div class="col-xl-4">
                        <div class="progress my-1">
                            <div class="progress-bar" role="progressbar"
                                aria-valuenow="{{ task.total_actual_progress }}" aria-valuemin="0" aria-valuemax="100"
                                style="width:{{ task.total_actual_progress }}%;">
                            </div>
                        </div>
                        <span class="badge badge-secondary my-1">期日：{{ task.target_date }}</span>
                        <span class="badge badge-secondary my-1">進捗：{{ task.total_actual_progress }}%</span>
                        <span class="badge badge-secondary my-1">残工数：{{ task.predicted_remaining_workload }}h</span>
                        <span class="badge badge-secondary my-1">残工数/日：{{ task.predicted_workload_per_day }}h</span>
                    </div>
                </div>
            </div>
            <ul class="list-group list-group-flush">
                {% for item in task.actual_data.all %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xl-8">
                                {{ item.input_date }}
                            </div>
                            <div class="col-xl-4">
                                <span class="badge badge-secondary my-1">{{ item.actual_workload }}h</span>
                                <span class="badge badge-secondary my-1">{{ item.progress }}%</span>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/Chart.min.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'js/Chart.min.js' %}"></script>
<script type="text/javascript">
    const verticalLinePlugin = {
        getLinePosition: function (chart, pointIndex) {
            const meta = chart.getDatasetMeta(0); // first dataset is used to discover X coordinate of a point
            const data = meta.data;
            return data[pointIndex]._model.x;
        },
        renderVerticalLine: function (chartInstance, pointIndex) {
            const lineLeftOffset = this.getLinePosition(chartInstance, pointIndex);
            const scale = chartInstance.scales['y-axis-0'];
            const scalex = chartInstance.scales['x-axis-0'];
            const context = chartInstance.chart.ctx;
            // render vertical line
            context.beginPath();
            context.strokeStyle = '#ff0000';
            context.moveTo(lineLeftOffset, scale.top);
            context.lineTo(lineLeftOffset, scale.bottom);
            context.stroke();
            // write label
            context.fillStyle = "#ff0000";
            context.textAlign = 'center';
            context.fillText('▼', lineLeftOffset, scale.top);
        },
        afterDatasetsDraw: function (chart, easing) {
            if (chart.config.lineAtIndex) {
            chart.config.lineAtIndex.forEach(pointIndex => this.renderVerticalLine(chart, pointIndex));
            }
        }
    };
    Chart.plugins.register(verticalLinePlugin);
    var myLineChart;
    var drawGraph = function(param) {
        $('#myChart').hide();
        $('#graph_loading').show();
        $.ajax({
            url:'{% url "main:top_graph_data" %}' + '?param=' + param,
            type:'GET'
        })
        // Ajaxリクエストが成功した時発動
        .done( (data) => {
            if (myLineChart){
                myLineChart.destroy();
            }
            $('#myChart').show();
            var ctx = document.getElementById("myChart").getContext("2d");
            myLineChart = new Chart(ctx, data);
            $('#graph_loading').hide();
        });
    };
    $(document).ready(function () {
        drawGraph('total')
    });
    $("#button_graph_total").click(function () {
        drawGraph('total');
    }); 
    $("#button_graph_perday").click(function () {
        drawGraph('perday');
    });
    $("#button_graph_actual").click(function () {
        drawGraph('actual');
    });
</script>
{% endblock %}